info:
  app:
    name: babbage-example

babbage:
  status:
    git:
      enabled: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: loggers, info, health
    loggers:
      enabled: true

