name: "Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:

  build:

    name: Build modules
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build & Run Tests
      run: |
        ./gradlew check